project:
  type: website
  output-dir: docs
website:
  title: "Melissa Draves"
  
  navbar:
    twitter-card: true
    background: palegreen
    foreground: dark
    left:
      - href: index.qmd
        text: Home

      - href: about.qmd 
        text: Background
       
      - href: projects.qmd 
        text: Projects
      
      - href: presentation.qmd
        text: Presentations
       
      - href: papers.qmd 
        text: Papers


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

